# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Amir Hossein Kohanpur
title: Ph.D. Candidate in Civil Engineering at University of Illinois at Urbana-Champaign
email: kohanpu2@illinois.edu
website: amirkohanpur.github.io

# Social links
github_username:  amirkohanpur
twitter_username: amirkohanpur
linkedin_username: amirkohanpur
orcid_username: 0000-0002-7132-3072

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
 I am Ph.D. candidate in the Department of Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign. My research focuses on modeling of multiphase flow in permeable media in different scales. 
 
 Please check out my [Google Scholar](https://scholar.google.com/citations?user=iX1JvlgAAAAJ&hl=en) profile for the updated list of publications.
 
 Research interests:
 <mark>flow in porous media</mark> <mark>carbon sequestrion</mark> <mark>parallel computing</mark> <mark>computational fluid dynamics</mark>

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# More Section
more_title: Honors & Awards
more_content: | 
  - Graduate College Conference Presentation Award, University of Illinois at Urbana-Champaign, 2020
  - Graduate College Conference Travel Award, University of Illinois at Urbana-Champaign, 2019
  - Recipient of the Graduate Teaching Assistantship,  University of Illinois at Urbana-Champaign, 2017-present
  - Recipient of the Graduate Research Assistantship,  University of Illinois at Urbana-Champaign, 2015-present
  - Granted the membership of Iran’s National Elites Foundation, 2011-present
  - Winner of the 3rd Place in 16th National Mechanical Engineering Olympiad, Iran, 2011
  - Winner of the 2nd Place in National Engineering Contest on National Broadcasting, Iran, 2011
  - Ranked 35th among 15,000 students in Nationwide M.Sc. Entrance Exam in Mechanical Engineering, Iran, 2011

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
