# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Amir Hossein Kohanpur
title: Ph.D. Candidate in Civil Engineering at University of Illinois at Urbana-Champaign
email: kohanpu2@illinois.edu
website: amirkohanpur.github.io

# Social links
github_username:  amirkohanpur
twitter_username: amirkohanpur
linkedin_username: amirkohanpur
orcid_username: 0000-0002-7132-3072

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am Ph.D. candidate in the Department of Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign.
 My research focuses on improving pore-scale models in studying two-phase flow in permeable media.
 
 Research interests: <mark>flow in porous media</mark> <mark>carbon sequestrion</mark> <mark>parallel computation</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  These are some of my hobbies:
   - Traveling
   - Photography
   - Tennis

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
